# Generated by Django 3.1.5 on 2021-02-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='created',
            new_name='created_date',
        ),
    ]
